# Generated by Django 2.2 on 2019-08-27 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250, null=True)),
            ],
            options={
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Responsables',
            },
        ),
        migrations.CreateModel(
            name='Tipo_producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos_Productos',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('responsable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Responsable')),
                ('abreviacion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'areas',
            },
            bases=('api.responsable',),
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('responsable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Responsable')),
                ('cedula', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'personas',
            },
            bases=('api.responsable',),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50, null=True)),
                ('serialnb', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('fecha_compra', models.DateField()),
                ('valor_compra', models.FloatField()),
                ('estado_actual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Estado')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Tipo_producto')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Responsable')),
            ],
            options={
                'verbose_name_plural': 'productos',
            },
        ),
    ]
